### ISSUE TITLE
openldap authentication

### ISSUE THREAD

**Issue by kevkha** [sameersbn/docker-squid#14]
Has anyone tried to enable ldap authentication with `osixia/docker-openldap`? After successfully ldapadd and ldapsearch the user but not able to make it work with the below settings in `squid.conf`.

```
auth_param basic program /usr/lib/squid3/basic_ldap_auth -v 3 -Z -b "dc=example,dc=com" -f "uid=%s" -h ldap.example.com
auth_param basic children 5 startup=5 idle=1
auth_param basic realm Squid proxy-caching web server
auth_param basic credentialsttl 8 hours
acl ldap_auth proxy_auth REQUIRED
http_access allow ldap_auth
```

I tested connectivity using the authentication module and it yields a hang
`/usr/lib/squid3/basic_ldap_auth -v 3 -Z -b "dc=example,dc=com" -f "uid=%s" -h ldap.example.com`

**Comment by kevkha** [comment]
I tried with a basis ncsa auth but it also yields a hang
`root@661122c96097:/# /usr/lib/squid3/basic_ncsa_auth /etc/squid3/passwd`

**Comment by kevkha** [comment]
I resolved by using this line.

```
auth_param basic program /usr/lib/squid3/basic_ldap_auth -b "dc=example,dc=com" -D "cn=admin,dc=example,dc=com" -w {password} -f "uid=%s" -h ldap.example.com
```

**Comment by sameersbn** [comment]
Sorry for not helping you resolve the issue. Unfortunately I have no expertise dealing with LDAP.
Glad that you do the issue resolved and thanks for sharing the resolution. I'm surely it will be helpful to other users :beers:

**Comment by kevkha** [comment]
No worries and thanks for your feedback mate. Great learning experience indeed. Many thanks to you for making this easy to use docker image. Cheers :beers:
