### ISSUE TITLE
Squid.conf not mounting

### ISSUE THREAD

**Issue by michaelkeevildown** [sameersbn/docker-squid#17]
When I try to mount the squid.conf with this docker config line I get an empty location:

```
--volume /local/location/to/squid.conf:/etc/squid3/squid.conf \
```

Is this the correct location for the newest build of squid?

**Comment by TalasZh** [comment]
output of docker inspect shows `/etc/squid3/` wasn't declared as volume

```
...
            "Cmd": null,
            "Image": "sameersbn/squid:3.3.8-22",
            "Volumes": {
                "/var/spool/squid3": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/sbin/entrypoint.sh"
            ],
            "OnBuild": null,
...
```

**Comment by TalasZh** [comment]
I'm running `sameersbn/squid:3.3.8-22` and works fine

**Comment by sameersbn** [comment]
@michaelkeevildown Sorry for the lateness of my response.

I think you have misunderstood the docs. `/local/location/to/squid.conf` should be an existing file, the image will not create it for you. If the file does not exist, then docker will create an empty directory and mount it at `/etc/squid3/squid.conf`. As you can imagine this is not expected by squid.

Try the following instead:

```bash
curl -LO https://raw.githubusercontent.com/sameersbn/docker-squid/master/squid.conf
docker run ... \
  --volume $PWD/squid.conf:/etc/squid3/squid.conf \
  sameersbn/squid:3.3.8-23
```

**Comment by sameersbn** [comment]
Please re-open if you need further assistance
