### ISSUE TITLE
The latest image doesnt has squid.conf

### ISSUE THREAD

**Issue by vinchauhan** [sameersbn/docker-squid#18]
docker inspect sameersbn/squid:3.3.8-23 - doesnt shows any exposed file to be mouted to local host

**Comment by sameersbn** [comment]
@vinchauhan you can mount a custom squid configuration at `/etc/squid3/squid.conf`. Unless you mount such a volume, docker inspect will now show this in its output. Please see https://github.com/sameersbn/docker-squid#configuration for more information.
