### ISSUE TITLE
HTTPS Caching

### ISSUE THREAD

**Issue by ekhoury2000** [sameersbn/docker-squid#19]
hi @sameersbn ,

i was testing your image, and it seems not to be caching https.

i fixed the max object size for caching and its caching ftp and http but not https.

Anything i might have missed?

Thanks

**Comment by canit00** [comment]
Curious as to why you want to cache HTTPs traffic in the first place. Did you enable SSL Bump and decrypting traffic?

**Comment by ekhoury2000** [comment]
@canit00 i want to cache all traffic like youtube traffic, etc......

i did not change anything in the conf file except for the max object size.

Thanks

**Comment by canit00** [comment]
@ekhoury2000 Okay, however, that's now how it works. To cache HTTPs you have to do much more then using the default config (at least what he's got here). If you want to enable caching read [squid documentation](http://wiki.squid-cache.org/ConfigExamples/Intercept/SslBumpExplicit) if you haven't already and will need to rebuild the image and deploy. Good luck!

**Comment by sameersbn** [comment]
caching HTTPS traffic essentially involves intercepting the HTTPS traffic which can be classified as a man-in-a-middle attack. As pointed to by @canit00, to achieve this you need to configure squid accordingly. The squid build installed in this image has support for SSL and you should be able to make the required changes.
