### ISSUE TITLE
Reload squid.conf

### ISSUE THREAD

**Issue by vertangelx** [sameersbn/docker-squid#5]
After editing `squid.conf` by adding `http_access allow all` as a quick test to allow all IP addresses to connect, how can the new conf be loaded? `service squid3 reload` does not seem to work as squid3 is not found as one of the "services"

**Comment by sameersbn** [comment]
@vertangelx `kill -s  HUP 1` does the job

**Comment by sameersbn** [comment]
@vertangelx The image has be changed quite a bit now with the following changes:

- configuration options have been removed
- customized `squid.conf` should be mounted at `/etc/squid3/squid.conf`. This means that any changes to the `squid.conf` file can be reloaded using `docker kill -s HUP squid`

I am closing this issue. Please reopen if you have any issues.
