### ISSUE TITLE
Spin a new container version of the latest 4.6

### ISSUE THREAD

**Issue by elico** [sameersbn/docker-squid#56]
Squid has been for quite some time on the 4.6 can you upgrade the container to 4.6 latest stable?
.. I forgot to mention that there is no DEB file from Ubuntu for it.

**Comment by modem7** [comment]
4.10 now

**Comment by elico** [comment]
@modem7 Thanks!!

**Comment by modem7** [comment]
Sorry, I meant 4.10 has been released, but the container needs to be updated

**Comment by elico** [comment]
@modem7 hoo.
Thanks for the efforts!!!
