### ISSUE TITLE
ACL

### ISSUE THREAD

**Issue by maqsoodumt** [sameersbn/docker-squid#7]
How to manage ACLs.....

**Comment by sameersbn** [comment]
@maqsoodumt you need to configure them in `squid.conf`. Refer to https://github.com/sameersbn/docker-squid#configuration.

**Comment by maqsoodumt** [comment]
Thanks again 4 your response and sorry for interrupting u......am unable to
save changes ins squid.conf....can u plz help in detail....

On Wed, Sep 16, 2015 at 9:50 AM, Sameer Naik <notifications@github.com>
wrote:

> @maqsoodumt <https://github.com/maqsoodumt> you need to configure them in
> squid.conf. Refer to
> https://github.com/sameersbn/docker-squid#configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-squid/issues/7#issuecomment-140626055>
> .
>



-- 
Maqsood Ahmad
Asst. Manager Networks, UMT
0334-9776102

**Comment by maqsoodumt** [comment]
Dear Sameer!

Hope u r doing best.....I am Maqsood Ahmad, from Lahore,.....working as
Asst. Manager Networks@umt.edu.pk.......am exploring containger
technology.....in short, am using your "sameersbn/squid:3.3.8" working
fine.....but I can't mount and edit "/etc/squid3/squid.conf" file to
add/modyfy my ACLs n other stuff.....Plz help how to do that.......

FYI:

root@DoCon:~# docker im
images  import
root@DoCon:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED
    VIRTUAL SIZE
sameersbn/squid     3.3.8               e6b98d4632e2        2 weeks ago
    214.5 MB

root@DoCon:~# docker ps -a
CONTAINER ID        IMAGE                   COMMAND                CREATED
            STATUS              PORTS                    NAMES
a9ed6d2c90bc        sameersbn/squid:3.3.8   "/sbin/entrypoint.sh   16
minutes ago      Up 10 minutes       0.0.0.0:3128->3128/tcp   squid

root@DoCon:~# docker -v
Docker version 1.7.0, build 0baf609

root@DoCon:~# docker info
Containers: 1
Images: 15
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 986.9 MiB
Name: DoCon
ID: GASE:O3A6:QTP7:LJPO:K66Q:VBID:QECJ:QMZM:AY7U:3Q7Q:TDKJ:2L5X
WARNING: No swap limit support
root@DoCon:~#




On Wed, Sep 16, 2015 at 3:08 PM, Maqsood Ahmad <maqsoodumt@gmail.com> wrote:

> Thanks again 4 your response and sorry for interrupting u......am unable
> to save changes ins squid.conf....can u plz help in detail....
>
> On Wed, Sep 16, 2015 at 9:50 AM, Sameer Naik <notifications@github.com>
> wrote:
>
>> @maqsoodumt <https://github.com/maqsoodumt> you need to configure them
>> in squid.conf. Refer to
>> https://github.com/sameersbn/docker-squid#configuration.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sameersbn/docker-squid/issues/7#issuecomment-140626055>
>> .
>>
>
>
>
> --
> Maqsood Ahmad
> Asst. Manager Networks, UMT
> 0334-9776102
>



-- 
Maqsood Ahmad
Asst. Manager Networks, UMT
0334-9776102

**Comment by sameersbn** [comment]
1. Download the squid.conf file `wget https://raw.githubusercontent.com/sameersbn/docker-squid/master/squid.conf`
2. Start squid using docker
   ```bash
   docker run --name squid -d --restart=always \
  --publish 3128:3128 \
  --volume $PWD/squid.conf:/etc/squid3/squid.conf \
  --volume /srv/docker/squid/cache:/var/spool/squid3 \
  sameersbn/squid:3.3.8
  ```
3. Edit `squid.conf` on the host as required
4. Reload the squid configuration for the changes to take effect `docker kill -s HUP squid`

For information on how to configure squid please refer the squid documentation.

**Comment by maqsoodumt** [comment]
Thanks a lot dear for such super and superb response.....let me try
first.....will respond in detail.......

On Thu, Sep 17, 2015 at 10:55 AM, Sameer Naik <notifications@github.com>
wrote:

>
>    1. Download the squid.conf file wget
>    https://raw.githubusercontent.com/sameersbn/docker-squid/master/squid.conf
>    2. Start squid using docker bash docker run --name squid -d
>    --restart=always \ --publish 3128:3128 \ --volume
>    $PWD/squid.conf:/etc/squid3/squid.conf \ --volume
>    /srv/docker/squid/cache:/var/spool/squid3 \ sameersbn/squid:3.3.8
>    3. Edit squid.conf on the host as required
>    4. Reload the squid configuration for the changes to take effect docker
>    kill -s HUP squid
>
> For information on how to configure squid please refer the squid
> documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-squid/issues/7#issuecomment-140976521>
> .
>



-- 
Maqsood Ahmad
Asst. Manager Networks, UMT
0334-9776102

**Comment by maqsoodumt** [comment]
Oh my God!!!!.................I did it....Thanks a lot
Sameer!!!!...............u know I was working on this project since couple
of day and was really sleepless, because was unable to modify default
setting in squid.conf.....one thing more do u suggest n recomment to
running squid as proxy server @University lever in as docker image?

Thanks n Regards'
Maqsood

On Thu, Sep 17, 2015 at 11:01 AM, Maqsood Ahmad <maqsoodumt@gmail.com>
wrote:

> Thanks a lot dear for such super and superb response.....let me try
> first.....will respond in detail.......
>
> On Thu, Sep 17, 2015 at 10:55 AM, Sameer Naik <notifications@github.com>
> wrote:
>
>>
>>    1. Download the squid.conf file wget
>>    https://raw.githubusercontent.com/sameersbn/docker-squid/master/squid.conf
>>    2. Start squid using docker bash docker run --name squid -d
>>    --restart=always \ --publish 3128:3128 \ --volume
>>    $PWD/squid.conf:/etc/squid3/squid.conf \ --volume
>>    /srv/docker/squid/cache:/var/spool/squid3 \ sameersbn/squid:3.3.8
>>    3. Edit squid.conf on the host as required
>>    4. Reload the squid configuration for the changes to take effect docker
>>    kill -s HUP squid
>>
>> For information on how to configure squid please refer the squid
>> documentation.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sameersbn/docker-squid/issues/7#issuecomment-140976521>
>> .
>>
>
>
>
> --
> Maqsood Ahmad
> Asst. Manager Networks, UMT
> 0334-9776102
>



-- 
Maqsood Ahmad
Asst. Manager Networks, UMT
0334-9776102

**Comment by sameersbn** [comment]
@maqsoodumt Sure. I don't see any reason not to.

**Comment by maqsoodumt** [comment]
Thanks dear 4 all your support n suggestions....may I know a bit about u,
your expertise, interest and hobbies.....

On Thu, Sep 17, 2015 at 12:18 PM, Sameer Naik <notifications@github.com>
wrote:

> @maqsoodumt <https://github.com/maqsoodumt> Sure. I don't see any reason
> not to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-squid/issues/7#issuecomment-140990140>
> .
>



-- 
Maqsood Ahmad
Asst. Manager Networks, UMT
0334-9776102

**Comment by sameersbn** [comment]
I like close issues.

**Comment by maqsoodumt** [comment]
U mean binary/digital 0/1?.......what about Indo-Pak relations?

On Thu, Sep 17, 2015 at 1:16 PM, Sameer Naik <notifications@github.com>
wrote:

> I like close issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-squid/issues/7#issuecomment-141000279>
> .
>



-- 
Maqsood Ahmad
Asst. Manager Networks, UMT
0334-9776102

**Comment by sameersbn** [comment]
That's on issue that does not seem will be resolved anytime soon.

**Comment by maqsoodumt** [comment]
U know what  Vajpayee ji, ex Indian PM, said once while visiting Pk: "f
riends can be changed but neighbours cannot be"...

On Thu, Sep 17, 2015 at 5:49 PM, Sameer Naik <notifications@github.com>
wrote:

> That's on issue that does not seem will be resolved anytime soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-squid/issues/7#issuecomment-141071106>
> .
>



-- 
Maqsood Ahmad
Asst. Manager Networks, UMT
0334-9776102
